name: Build, deploy and release

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Create a GitHub release'
        default: true
        required: true
        type: boolean
      latest:
        description: 'Make release latest'
        default: true
        required: true
        type: boolean
      deploy:
        description: 'Copy artifacts to deploy path'
        default: true
        required: true
        type: boolean
      deploy-path:
        description: 'Path to copy artifacts to'
        default: '~/build/'
        required: false
        type: string
  pull_request:
    branches:
      - master

jobs:
  master-deploy:
    uses: NeverMined-Entertainment/CI-CD/.github/workflows/master-deploy.yml@master
    with:
      release: ${{ github.event_name == 'pull_request' || inputs.release }}
      latest: ${{ github.event_name == 'pull_request' || inputs.latest }}
      deploy: ${{ github.event_name == 'pull_request' || inputs.deploy }}
      deploy-path: ${{ inputs.deploy-path || '~/build/' }}
    secrets:
      token: ${{ secrets.TOKEN }}